Set up grafana to automatically take snapshots of SPD global dashboar…
redhat-cop/pelorus pull request #210
Opened 2020-10-05 14:45 UTC by etsauer

…d on a schedule

## Describe the behavior changes introduced in this PR

This PR adds two jobs to the pelorus helm chart.

* The first jobs is a post-install/post-upgrade hook that creates an apikey in grafana and saves it as a secret
* The second job is a CronJob that uses the apikey to create snapshots in Grafana. Currently it only snapshots the global SDP dashboard.

Outstanding items:
* Currently the snapshot job just creates the snapshot and logs the URL in the job pod. Some further work will need to be done to make that URL more easily available.

## Linked Issues?

resolves #47 

## Testing Instructions

Deploy Pelorus, overloading the `snapshot_schedule` variable to something quick, like `*/2 * * * *`, then wait 2 minutes, and check that the cronjob runs. Check the pod logs, and copy the URL into the browser in incognito mode to ensure that an unauthenticated user can view the snapshot

@redhat-cop/mdt

2020-10-30 16:07 UTC, themoosman commented
@etsauer You're going to have to rebase this branch.

2020-11-03 14:37 UTC, etsauer commented
@themoosman updated.

2020-11-10 11:58 UTC, jtudelag commented
Btw, in case this is useful, ssed this command to manually  trigger a cronjob:

`kubectl create job --from=cronjob/dashboard-snapshots manual-dashboard-snapshots`

2020-11-10 15:28 UTC, etsauer commented
@themoosman this is ready to test again.

2020-11-11 17:24 UTC, themoosman commented
There seems to be a race condition with the `grafana-create-apikey` job.  It is executing before the grafana instance is up and healthy.  As such, the `grafana-apikey` isn't created.  When I put a `60` hard sleep in the `grafana-create-apikey` job, everything worked just fine.

2020-11-11 17:33 UTC, themoosman requested changes
See comment:  https://github.com/redhat-cop/pelorus/pull/210#issuecomment-725553288

2020-11-12 21:34 UTC, etsauer commented
@themoosman ready to test again.

2020-11-13 14:22 UTC, themoosman commented
Okay, here is what I found.  If I use the default version of Grafana 3.5.0, it works fine.  However, if I upgrade the Grafana operator to 3.6.0 (the UI prompts me) I see the snapshot jobs fail.  I even tried updating the `grafana-subscription.yaml` to 3.6.0 then doing a helm install.  When doing that I still see the job failure.

2020-11-13 14:23 UTC, etsauer commented
@themoosman ok. for that I think we should add a new story to our backlog to upgrade/test Grafana 3.6.0

2020-11-13 14:25 UTC, themoosman commented
> @themoosman ok. for that I think we should add a new story to our backlog to upgrade/test Grafana 3.6.0

I added one a few days ago.

2020-11-13 14:27 UTC, etsauer commented
ok, great. then are you waiting on any other changes for this PR?

2020-11-13 14:42 UTC, themoosman commented
> ok, great. then are you waiting on any other changes for this PR?

No, I added a note to that issue about this PR.

2020-11-13 14:43 UTC, themoosman approved these changes
LGTM

2020-11-13 14:43 UTC, merged