Service now exporter
redhat-cop/pelorus pull request #211
Opened 2020-10-05 18:41 UTC by malacourse

## Describe the behavior changes introduced in this PR
This PR adds support for exporting ServiceNow incidents or problems using the ServcieNow API.  This will create data for failure time resolution.

## Linked Issues?

resolves #126 

## Testing Instructions
With a developer account you can create a ServiceNow instance for testing: https://developer.servicenow.com/dev.do

1) Start the service now instance
2) Create some resolved incidents with the category 'software'
3) set your environment variables similar to the following:
      SERVER='https://dev59871.service-now.com'
      TRACKER_QUERY='/api/now/table/incident?sysparm_fields=closed_at%2Copened_at%2Cstate%2Cnumber&state=6&category='
      USER=admin
      TOKEN=<password>
      PROJECT=software
      TRACKER_PROVIDER=servicenow

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

2020-10-06 13:34 UTC, etsauer requested changes
@malacourse made a couple comments on the variable names. In addition two major items that need addressed>

1. When I run this I get the following error:

```
Exception has occurred: TypeError
__init__() takes 4 positional arguments but 5 were given
  File "/home/esauer/src/pelorus/exporters/failure/collector_servicenow.py", line 22, in __init__
    super().__init__(server, user, apikey, project)
  File "/home/esauer/src/pelorus/exporters/failure/app.py", line 21, in getCollector
    return ServiceNowFailureCollector(username, token, tracker_api, project)
  File "/home/esauer/src/pelorus/exporters/failure/app.py", line 38, in <module>
    collector = TrackerFactory.getCollector(username, token, tracker_api, project, tracker_provider)
```

2. We need a method of figuring out the app name related to a ticket. See the updates made to the Jira collector for a reference.

2020-10-06 13:34 UTC, etsauer commented on docs/Configuration.md
> +| `TACKER_PROVIDER` | no | Set the type of failure provider. One of `jira`, `servicenow` | `jira` |
Let's just call this `PROVIDER` to be consistent with other exporters

2020-10-06 13:34 UTC, etsauer commented on docs/Configuration.md
> +| `TRACKER_QUERY` | no | Used for ServiceNow integration, query used to gather incidents or problems. ex: "/api/now/table/incident?sysparm_fields=closed_at%2Copened_at%2Cstate%2Cnumber&state=6&catego
let's call this `INCIDENT_QUERY`

2020-10-06 19:52 UTC, etsauer commented on exporters/failure/collector_servicenow.py
> +            tracker_issue = TrackerIssue(issue.get('number'), created_ts, resolution_ts)
This line needs to include an app name, like so:

```
tracker_issue = TrackerIssue(issue.key, created_ts, resolution_ts, self.get_app_name(issue))
```

2020-10-15 20:34 UTC, etsauer requested changes
ok, so a couple of things here.... it looks like there are several different sys_params for "opening/creating" and "resolving/closing" an incident. Are we using the right ones?

second, I think we need to get rid of `TRACKER_QUERY` and instead build the query ourselves using the APP_LABEL parameter. This is both because then it works more the way the Jira provider does, AND because it makes me a little worried about security holes we might be opening by having the user define a custom query.

also, in the current verison, you need to pass the value of `APP_LABEL` twice, once in the variable and once in the query, which I think will be confusing

2020-10-15 20:34 UTC, etsauer commented on docs/Configuration.md
> +| `APP_LABEL_FIELD` | yes | ServiceNow field used for the Application label. ex: "u_applabel" | unset |
This should just be `APP_LABEL`

2020-10-22 18:51 UTC, malacourse commented
Changes have been pushed per review

2020-10-29 16:05 UTC, malacourse commented
I realized I pushed to wrong branch.  Updates are now in.

2020-10-29 17:06 UTC, etsauer commented
@malacourse so it looks like two things are happening now when I call the exporter.

First it appears to be returning the same results multiple times per call:

```
$ curl localhost:8080 | grep 'INC0010010'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_resolution_timestamp{app="unknown",issue_number="INC0010010"} 1.603796262e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
100  2failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
51k  10failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
0  251failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
k    0     0   118kfailure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
      0 failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
 0:00:02  failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
0:00:02 failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
--:--:-failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
-  118k
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
failure_creation_timestamp{app="unknown",issue_number="INC0010010"} 1.603796236e+09
```

Second, the incident that i searched for above should have been labelled `app=basic-spring-boot` per the screenshot below, and it wasn't.

![inc-spring-boot](https://user-images.githubusercontent.com/4500758/97607540-81c14980-19e7-11eb-91b4-de4e887bcff4.png)

2020-11-10 20:37 UTC, etsauer approved these changes
lgtm

2020-11-10 20:39 UTC, merged